server:
  port: 8080

spring:
  application:
    name: charlee

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        highlight_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    com.efa73.trackee: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace