spring:
  config:
    activate:
      on-profile: dev
    import:
      - vault://

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    vault:
      uri: ${VAULT_URI}
      #      host: ${VAULT_HOST}
      #      port: ${VAULT_PORT}
      #      scheme: ${VAULT_SCHEME}
      authentication: ${VAULT_AUTHENTICATION}
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: ${VAULT_BACKEND}
        application-name: charlee
        profiles: ${spring.profiles.active}
#        kv-version: 2
#        default-context: ${VAULT_DEFAULT_CONTEXT}
#        profile-separator: "/"

logging:
  level:
    com.efa73.trackee: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
