spring:
  application:
    name: charlee

  config:
    import:
      - optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    vault:
      enabled: false

logging:
  level:
    com.efa73.trackee: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace