spring:
  config:
    import:
      - vault://

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    vault:
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      scheme: ${VAULT_SCHEME}
      authentication: ${VAULT_AUTHENTICATION}
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: ${VAULT_BACKEND}
        default-context: ${VAULT_DEFAULT_CONTEXT}

logging:
  level:
    com.efa73.trackee: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace